CREATE TYPE [dbo].[AdjudicatedClaims] AS TABLE
(
	Line INT,
	ClaimId BIGINT,
	ContractId BIGINT,
	ServiceTypeId BIGINT,
	ClaimStatus INT,
	AdjudicatedValue MONEY,
	ClaimTotalCharges MONEY,
	IsClaimChargeData BIT,
	IsInitialEntry BIT,
	PaymentTypeDetailId BIGINT,
	PaymentTypeId INT,
	IntermediateAdjudicatedValue FLOAT,
	ExpressionResult FLOAT,
	Expression VARCHAR(5000),
	ExpandedExpression VARCHAR(8000),
	CustomExpressionResult FLOAT,
	CustomExpression VARCHAR(5000),
	CustomExpandedExpression VARCHAR(8000),
	IsFormulaError BIT,
	MicrodynEditErrorCodes VARCHAR(500),
	MicrodynPricerErrorCodes INT,
	MicrodynEditReturnRemarks VARCHAR(1000),
	MedicareSequesterAmount MONEY NULL,
     MultiplierExpressionResult FLOAT,
     IsMultiplierFormulaError BIT,
     Multiplier INT,
     MultiplierExpandedExpression VARCHAR(8000),
     LimitExpressionResult FLOAT,
     IsLimitError BIT,
     LimitExpandedExpression VARCHAR(8000)
);
GO
