CREATE TABLE [dbo].[CmsLogs]
(
	[CmsLogId] [int] IDENTITY(1,1) NOT NULL,
	[InsertDate] [datetime] NULL,
	[Error] [varchar](4000) NULL,
PRIMARY KEY CLUSTERED 
(
	[CmsLogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
