CREATE TABLE [dbo].[ref.PaymentTypes](
	[PaymentTypeID] [bigint] NOT NULL,
	[PaymentTypeName] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[PaymentTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]