CREATE TABLE [dbo].[ref.FilterOperator](
	[OperatorID] [int] NOT NULL,
	[OperatorType] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[OperatorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]