
CREATE TABLE [dbo].[RTA_EdiRequests](
	[ID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[RequestInput] [VARCHAR](MAX) NOT NULL,
	[RequestDateTime] [DATETIME] NOT NULL,
	[StatementFrom] [DATETIME] NULL,
	[StatementTo] [DATETIME] NULL,
	[SSINumber] [INT] NULL,
	[PayerName] [VARCHAR](100) NULL,
	[PayerCode] [VARCHAR](100) NULL,
	[TotalCharges] [MONEY] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
